name: nip07signer
description: Sign with NIP-07 extension from the command line
version: 0.1.0
repository: https://github.com/zapstore/nip07signer

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  args: ^2.4.0
  cli_spin: ^1.0.1
  http: ^1.3.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
