name: nip07_signer
description: Sign with NIP-07 extension from the command line
version: 0.1.2
repository: https://github.com/purplebase/nip07_signer

environment:
  sdk: ^3.7.2

dependencies:
  args: ^2.4.0
  http: ^1.3.0
  models: ^0.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

dependency_overrides:
  models:
    git:
      url: https://github.com/purplebase/models
      ref: 1d75de2